services:
  postgres:
    image: postgres:13-alpine3.17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coursework-network

volumes:
  postgres_data: # Определяем volume

networks:
  coursework-network: # Определяем сеть
