spring:
  application:
    name: Coursework_vddmit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12341234
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 12341234
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      flywaydb: INFO
  file:
    name: logs/spring.log